// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aeolus-landing/BrandManifesto.tsx": () => import("../components/mockups/aeolus-landing/BrandManifesto.tsx"),
  "./components/mockups/aeolus-landing/CatalogFirst.tsx": () => import("../components/mockups/aeolus-landing/CatalogFirst.tsx"),
  "./components/mockups/aeolus-landing/ScaleAuthority.tsx": () => import("../components/mockups/aeolus-landing/ScaleAuthority.tsx"),
  "./components/mockups/aeolus-landing/TechnicalAuthority.tsx": () => import("../components/mockups/aeolus-landing/TechnicalAuthority.tsx")
};
